version: '3.9'
services:
  pepm-ui:
    image: pepm-ui:dev
    build:
      target: development
      context: .
    volumes:
      - ./src:/code/src
    env_file:
      - .env
    ports:
      - 3000:3000
