version: '3.9'
services:
  pepm-ui:
    image: pepm-ui:dev
    build:
      target: local
      context: .
    volumes:
      - ./src:/code/src
    env_file:
      - .env.local
    ports:
      - 3000:3000
