version: '3.9'
services:
  pepm-ui:
    image: ghcr.io/equinor/pepm-ui/pepm-ui:${IMAGE_TAG:-latest}
    build:
      target: production
      context: .
    environment:
      - REACT_APP_AAD_CLIENT_ID=REACT_APP_AAD_CLIENT_ID2
      - REACT_APP_AAD_TENANT_ID=REACT_APP_AAD_TENANT_ID2
      - REACT_APP_AAD_REDIRECT_URI=REACT_APP_AAD_REDIRECT_URI2
      - REACT_APP_BACKEND_URL=REACT_APP_BACKEND_URL2
      - REACT_APP_BACKEND_API_SCOPE=REACT_APP_BACKEND_API_SCOPE2
    ports:
      - 3000:3000
