/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/analoguemodels": {
    /** Get a list of all AnalogueModels */
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["AnalogueModelList"][];
          };
        };
      };
    };
    /** Create new Analogue Model */
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateAnalogueModelCommand"];
          "application/json": components["schemas"]["CreateAnalogueModelCommand"];
          "text/json": components["schemas"]["CreateAnalogueModelCommand"];
          "application/*+json": components["schemas"]["CreateAnalogueModelCommand"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["CreateAnalogueModelCommandResponse"];
          };
        };
      };
    };
  };
  "/api/analoguemodels/{id}": {
    /** Get AnalogueModel by id */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["AnalogueModelDetail"];
          };
        };
      };
    };
    /** Update AnalogueModel by Id */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateAnalogueModelCommandBody"];
          "application/json": components["schemas"]["UpdateAnalogueModelCommandBody"];
          "text/json": components["schemas"]["UpdateAnalogueModelCommandBody"];
          "application/*+json": components["schemas"]["UpdateAnalogueModelCommandBody"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["UpdateAnalogueModelCommandResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
    /** Delete a AnalogueModel by id */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description No Content */
        204: never;
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
    /** Patch a AnalogueModel by Id with new values */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["Operation"][];
          "application/json": components["schemas"]["Operation"][];
          "text/json": components["schemas"]["Operation"][];
          "application/*+json": components["schemas"]["Operation"][];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["PatchAnalogueModelCommandResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
  };
  "/api/analoguemodels/{id}/uploads": {
    /** Upload model files that is converted to PEPM models. */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            File?: string;
            FileType?: components["schemas"]["UploadFileType"];
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["UploadAnalogueModelCommandResponse"];
          };
        };
      };
    };
  };
  "/api/analoguemodels/{id}/convert": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["UploadAnalogueModelCommandResponse"];
          };
        };
      };
    };
  };
  "/api/analogues": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["AnalogueList"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateAnalogueCommand"];
          "application/json": components["schemas"]["CreateAnalogueCommand"];
          "text/json": components["schemas"]["CreateAnalogueCommand"];
          "application/*+json": components["schemas"]["CreateAnalogueCommand"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["CreateAnalogueCommandResponse"];
          };
        };
      };
    };
  };
  "/api/jobs": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["JobList"];
          };
        };
      };
    };
  };
  "/api/parameters": {
    /** Get a list of all Parameters */
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["ParameterList"][];
          };
        };
      };
    };
    /** Create new Parameter */
    post: {
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["CreateParameterCommand"];
          "application/json": components["schemas"]["CreateParameterCommand"];
          "text/json": components["schemas"]["CreateParameterCommand"];
          "application/*+json": components["schemas"]["CreateParameterCommand"];
        };
      };
      responses: {
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
  };
  "/api/parameters/{id}": {
    /** Get Parameter details by Id */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["ParameterDetail"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
    /** Update Parameter by Id */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["UpdateParameterCommandBody"];
          "application/json": components["schemas"]["UpdateParameterCommandBody"];
          "text/json": components["schemas"]["UpdateParameterCommandBody"];
          "application/*+json": components["schemas"]["UpdateParameterCommandBody"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["UpdateParameterCommandResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
    /** Delete a parameter by id */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description No Content */
        204: never;
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
    /** Patch a Parameter by Id with new values */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json-patch+json": components["schemas"]["Operation"][];
          "application/json": components["schemas"]["Operation"][];
          "text/json": components["schemas"]["Operation"][];
          "application/*+json": components["schemas"]["Operation"][];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["PatchParameterCommandResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["StringBaseResponse"];
          };
        };
      };
    };
  };
  "/api/uploads": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["UploadList"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AnalogueList: {
      /** Format: uuid */
      analogueId?: string;
      name?: string | null;
      description?: string | null;
    };
    AnalogueModelDetail: {
      /** Format: uuid */
      analogueModelId?: string;
      name?: string | null;
      description?: string | null;
      isProcessed?: boolean;
      sourceType?: components["schemas"]["AnalogueModelSourceType"];
      analogues?: components["schemas"]["AnalogueList"][] | null;
      fileUploads?: components["schemas"]["UploadList"][] | null;
    };
    AnalogueModelList: {
      /** Format: uuid */
      analogueModelId?: string;
      name?: string | null;
      description?: string | null;
      isProcessed?: boolean;
      sourceType?: components["schemas"]["AnalogueModelSourceType"];
    };
    /** @enum {string} */
    AnalogueModelSourceType: "Deltares" | "ResQML";
    CreateAnalogueCommand: {
      name?: string | null;
      description?: string | null;
    };
    CreateAnalogueCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["CreateAnalogueDto"];
    };
    CreateAnalogueDto: {
      /** Format: uuid */
      analogueId?: string;
      name?: string | null;
      description?: string | null;
    };
    CreateAnalogueModelCommand: {
      name?: string | null;
      description?: string | null;
      sourceType?: string | null;
    };
    CreateAnalogueModelCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["CreateAnalogueModelDto"];
    };
    CreateAnalogueModelDto: {
      /** Format: uuid */
      analogueModelId?: string;
      name?: string | null;
      description?: string | null;
    };
    CreateParameterCommand: {
      identifier?: string | null;
      name?: string | null;
      description?: string | null;
    };
    JobList: {
      /** Format: uuid */
      jobId?: string;
      name?: string | null;
      jobStatus?: components["schemas"]["JobStatus"];
      jobType?: components["schemas"]["JobType"];
    };
    /** @enum {string} */
    JobStatus: "Unknown" | "Created" | "Started" | "Running" | "Successful" | "Failed";
    /** @enum {string} */
    JobType: "Nrresqml" | "Nrchannel" | "Nrvariogram";
    Operation: {
      operationType?: components["schemas"]["OperationType"];
      path?: string | null;
      op?: string | null;
      from?: string | null;
      value?: Record<string, unknown> | null;
    };
    /** @enum {string} */
    OperationType: "Add" | "Remove" | "Replace" | "Move" | "Copy" | "Test" | "Invalid";
    ParameterDetail: {
      /** Format: uuid */
      parameterId?: string;
      identifier?: string | null;
      name?: string | null;
      description?: string | null;
    };
    ParameterList: {
      /** Format: uuid */
      parameterId?: string;
      identifier?: string | null;
      name?: string | null;
      description?: string | null;
    };
    PatchAnalogueModelCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["PatchAnalogueModelDto"];
    };
    PatchAnalogueModelDto: {
      /** Format: uuid */
      analogueModelId?: string;
      name?: string | null;
      description?: string | null;
    };
    PatchParameterCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["PatchParameterDto"];
    };
    PatchParameterDto: {
      /** Format: uuid */
      parameterId?: string;
      identifier?: string | null;
      name?: string | null;
      description?: string | null;
    };
    StringBaseResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: string | null;
    };
    UpdateAnalogueModelCommandBody: {
      name?: string | null;
      description?: string | null;
      sourceType?: string | null;
    };
    UpdateAnalogueModelCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["UpdateAnalogueModelDto"];
    };
    UpdateAnalogueModelDto: {
      /** Format: uuid */
      analogueModelId?: string;
      name?: string | null;
      description?: string | null;
      sourceType?: string | null;
    };
    UpdateParameterCommandBody: {
      identifier?: string | null;
      name?: string | null;
      description?: string | null;
    };
    UpdateParameterCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["UpdateParameterDto"];
    };
    UpdateParameterDto: {
      /** Format: uuid */
      parameterId?: string;
      identifier?: string | null;
      name?: string | null;
      description?: string | null;
    };
    UploadAnalogueModelCommandResponse: {
      success?: boolean;
      /** Format: int32 */
      count?: number | null;
      message?: string | null;
      validationErrors?: string[] | null;
      value?: components["schemas"]["UploadAnalogueModelDto"];
    };
    UploadAnalogueModelDto: {
      /** Format: uuid */
      uploadId?: string;
      uploadStatus?: components["schemas"]["UploadStatus"];
      processed?: boolean;
    };
    /** @enum {string} */
    UploadFileCategory: "InputModel" | "InputMetadata" | "ResQmlModel";
    /** @enum {string} */
    UploadFileType: "NetCDF" | "ResQMLEpc" | "ResQMLData";
    UploadList: {
      /** Format: uuid */
      uploadId?: string;
      originalFileName?: string | null;
      uploadStatus?: components["schemas"]["UploadStatus"];
      uploadFileType?: components["schemas"]["UploadFileType"];
      uploadFileCategory?: components["schemas"]["UploadFileCategory"];
      processed?: boolean;
    };
    /** @enum {string} */
    UploadStatus: "Started" | "ReadyForProcessing" | "Processing" | "Processed" | "Failed";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
