name: Deploy to Production

# Only one workflow in a concurrency group may run at a time
concurrency:
  group: test-concurrency
  cancel-in-progress: true

on:
  release:
    types: [created]

jobs:
    trigger-github-deployment:
      name: Trigger GitHub Deployment
      environment: prod
      runs-on: ubuntu-latest
      steps:
        - name: Start deployment to production
          run: echo "Deployment to production started"

    build-and-publish-release-to-prod:
      name: Build and publish containers for prod
      uses: ./.github/workflows/build-and-publish.yml
      needs: trigger-github-deployment
      with:
        Registry: ghcr.io
        ImageName: ${{ github.repository }}
        Tag: ${{ github.event.release.tag_name }}
        Environment: prod
      secrets: inherit
    
    deploy:
      name: Update deployment in Production
      needs: [trigger-github-deployment, build-and-publish-release-to-prod]
      uses: ./.github/workflows/deploy-to-radix.yml
      with:
        Environment: prod
        VersionTag: ${{ github.event.release.tag_name }}
      secrets:
        ClientId: ${{ secrets.CLIENT_ID }}
        TenantId: ${{ secrets.TENANT_ID }}