on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        default: latest
        type: string

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: echo "Tagging with ${{inputs.IMAGE_TAG}}"

      - name: Build Container Image
        run: IMAGE_TAG=${{inputs.IMAGE_TAG}} docker compose build

      - name: Publish Container Image
        run: IMAGE_TAG=${{inputs.IMAGE_TAG}} docker compose push

