on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: ${{inputs.ENVIRONMENT}}

    steps:
      - uses: actions/checkout@master
      - run: echo "Tagging with ${{inputs.ENVIRONMENT}}"

      - name: Build Container Image
        run: ENVIRONMENT=${{inputs.ENVIRONMENT}} docker compose build

      - name: Authenticate Against Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Publish Container Image
        run: ENVIRONMENT=${{inputs.ENVIRONMENT}} docker compose push
